services:
  blog_1:
    build: ./docker/httpd
    container_name: blog-1
    ports:
      - 8051:80

  blog_2:
    build: ./docker/httpd
    container_name: blog-2
    ports:
      - 8052:80

  blog_3:
    build: ./docker/httpd
    container_name: blog-3
    ports:
      - 8053:80

  load_balancer:
    build: ./docker/nginx
    container_name: blog-lb
    ports:
      - 8949:80
    # depends_on은 서비스의 시작 순서 보장, 서비스를 시작하기 전에 blog_1, blog_2, blog_3 서비스가 반드시 실행되어야 함을 지정
    depends_on:
      - blog_1
      - blog_2
      - blog_3

    # .yaml에서는 컨테이너 이름이 아니라 service의 이름
    links:
      - blog_1
      - blog_2
      - blog_3
    develop:
      watch:
        - action: sync+restart
          path: ./docker/nginx/default.conf
          target: /etc/nginx/conf.d/default.conf
